build:image:
  script:
    - apk add --no-cache docker
    - python setup.py install
    - tutor plugins enable notes
    - tutor config save
    - tutor images build notes
  only:
    refs:
      - master
  tags:
    - private
  stage: build

deploy:image:
  script:
    - apk add --no-cache docker
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - python setup.py install
    - tutor plugins enable notes
    - tutor config save
    - tutor images push notes
  only:
    refs:
      - master
  tags:
    - private
  stage: deploy

deploy:pypi:
  script:
    - pip3 install -U setuptools twine==2.0.0
    - python3 setup.py sdist
    - twine upload --skip-existing dist/tutor-notes*.tar.gz
  only:
    refs:
      - master
  tags:
    - private
  stage: deploy
